version: "3.7"
services:
  opentogethertube-dev:
    image: opentogethertube_dev
    container_name: opentogethertube_dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    environment:
      - REDIS_HOST=redis_db
    healthcheck:
      test: "curl -f http://localhost:8080/ || exit 1"
    env_file: ../../env/development.env
    ports:
      - 8080:8080
      - 8888:8888
    links:
      - redis_db
    depends_on:
      - redis_db

  redis_db:
    container_name: opentogethertube_dev_redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "redis-cli ping"
    expose:
        - 6379
    volumes:
      - db-data-redis:/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

# shared volume
volumes:
  db-data-redis:
    driver: local