version: "3.7"
services:
  opentogethertube-dev:
    image: opentogethertube_dev
    container_name: opentogethertube_dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    environment:
      - REDIS_HOST=redis_db
      # - POSTGRES_DB_NAME=opentogethertubedev
      # - POSTGRES_DB_HOST=postgres_db
      # - POSTGRES_DB_PASSWORD=root
    healthcheck:
      test: "curl -f http://localhost:3001/ || exit 1"
    ports:
      - 8080:8080
      - 8888:8888
    links:
      - redis_db
      # - postgres_db
    depends_on:
      - redis_db
      # - postgres_db

  redis_db:
    container_name: opentogethertube_dev_redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "redis-cli ping"
    expose:
        - 6379
    volumes:
      - db-data-redis:/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  # postgres_db:
  #   container_name: opentogethertube_dev_postgres
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=opentogethertubedev
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - PGDATA=/tmp
  #   healthcheck:
  #     test: "pg_isready -U root"
  #   expose:
  #     - 5432
  #   volumes:
  #     - db-data-postgres:/var/lib/postgresql/data
  #   restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

# shared volume
volumes:
  db-data-redis:
    driver: local
  # db-data-postgres:
  #   driver: local