version: "3.7"
services:
  opentogethertube-dev:
    image: opentogethertube_dev
    container_name: opentogethertube_dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    environment:
      # - YOUTUBE_API_KEY=API_KEY_GOES_HERE # optional put it in env/development.env
      # nodejs
      - NODE_ENV=development
      - NODE_OPTIONS="--max-http-header-size=16000"
      # redis
      - REDIS_HOST=redis_db
      - REDIS_PASSWORD=redis
      # postgres
      - DATABASE_URL=postgres://root@db_opentogethertube_dev:5432
    healthcheck:
      test: "curl -f http://localhost:8080/ || exit 1"
    ports:
      - 8080:8080
    links:
      - redis_db
      - postgres_db
    depends_on:
      - redis_db
      - postgres_db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  redis_db:
    container_name: opentogethertube_dev_redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "redis-cli ping"
    expose:
        - 6379
    volumes:
      - dev_db_data:/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  postgres_db:
    container_name: opentogethertube_dev_postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=db_opentogethertube_dev
      - PGDATA=/var/lib/postgresql/data/db-dev
    healthcheck:
      test: "pg_isready -U root"
    expose:
      - 5432
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

# shared volume
volumes:
  dev_db_data:
    driver: local
