module.exports = {
  preset: "@vue/cli-plugin-unit-jest/presets/typescript-and-babel",
  moduleFileExtensions: [
    'js',
    'jsx',
    'ts',
    'tsx',
    'json',
    'vue',
  ],
  transform: {
    '^.+\\.vue$': 'vue-jest',
    '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
    '^.+\\.ts$': 'ts-jest',
    '^.+\\.js$': 'babel-jest',
  },
  transformIgnorePatterns: [
    // '/node_modules/',
    '!/(common|src)/',
    '/tests/unit/server/',
  ],
  rootDir: "../..",
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^common/(.*)$': '<rootDir>/../common/$1',
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: ['**/tests/unit/**/*.spec.(js|ts)|**/__tests__/*.(js|ts)'],
  testURL: 'http://localhost/',
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
  collectCoverage: true,
  coverageReporters: [
    "text-summary",
    "text",
    "json",
    "html",
  ],
  collectCoverageFrom: [
    '**/*.{js,ts,vue}',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/*.config.js',
    '!**/*.eslintrc.js',
    '!**/coverage/**',
    '!**/config/**',
    '!**/migrations/**',
    '!**/models/**',
    '!**/seeders/**',
    '!**/server/**',
    '!**/tests/**',
    '!src/App.vue',
    '!src/plugins/vuetify.js',
    '!src/(main|router).js',
    '!*.js',
  ],
};
