# fly.toml app configuration file generated for ott-test on 2023-07-13T14:49:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ott-balancer-test"
primary_region = "ewr"

[build]
dockerfile = "deploy/balancer.Dockerfile"

[http_service]
internal_port = 8081
force_https = true
# auto_stop_machines = true
# auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "10s"
path = "/api/status"
