export default {
	preset: "ts-jest",
	testEnvironment: "node",
	transform: {
		"^.+\\.jsx?$": "babel-jest",
	},
	rootDir: "../..",
	testMatch: ["**/tests/unit/**/*.spec.(js|ts)|**/__tests__/*.(js|ts)"],
	testPathIgnorePatterns: ["/node_modules/", "/dist/", "/coverage/", "/ts-out/"],
	watchPlugins: ["jest-watch-typeahead/filename", "jest-watch-typeahead/testname"],
	// collectCoverage: true,
	coverageReporters: ["text-summary", "text", "json", "html"],
	collectCoverageFrom: [
		"**/*.{js,ts}",
		"!**/node_modules/**",
		"!**/dist/**",
		"!**/*.config.js",
		"!**/*.eslintrc.js",
		"!**/config/**",
		"!**/migrations/**",
		"!**/models/**",
		"!**/seeders/**",
		"!**/coverage/**",
		"!**/tests/**",
		"!**/src/**",
		"!app.js",
	],
	setupFilesAfterEnv: ["./tests/unit/jest.setup.redis-mock.js"],
};
