name: Report a Bug
description: Is there something not working like you expected? Let us know!
labels: [bug, uncomfirmed]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Create a room...
      2. Add a video...
      3. Click...
      4. See error...
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Environment
    description: Mark the appropriate boxes. If you don't know if the statement applies, leave it blank.
    options:
    - label: This happens on the official site, opentogethertube.com
    - label: This happens using a self-hosted version.
    - label: I'm using the docker image.
- type: input
  attributes:
    label: Room name or URL
    description: If you're on the official site, please provide the room name or url so I can track down the logs. Otherwise, leave blank.
  validations:
    required: false
- type: input
  attributes:
    label: Video URL
    description: If you're having trouble with video playback, please provide the video URL. Otherwise, leave blank.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Version Numbers? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
