[package]
name = "ott-balancer-protocol"
version = "0.14.1"
edition = "2021"

[dependencies]
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
typeshare.workspace = true
uuid.workspace = true
