FROM node:14-buster

VOLUME ["/usr/app"]
# Create app directory
WORKDIR /usr/app/

RUN apt-get update && apt-get install -y netcat && apt-get clean autoclean && rm -rf /var/lib/apt/lists/*
RUN npm rebuild

# Environnement variable redis/postgres/webport
ENV REDIS_PORT 6379
# Environnement variable nodejs
ENV NODE_ENV production
ENV LOG_LEVEL debug

# Healthcheck API, WEB, REDIS
HEALTHCHECK CMD ( curl -f http://localhost:8080/ || exit 1 )

# Start Server
CMD ["/bin/sh", "docker/scripts/wait_for_db.sh", "postgres_db:5432", "--", "npm", "run", "dev"]
