# Compose override for running in e2e environment
services:
  opentogethertube:
    build:
      target: docker-test-stage
    environment:
      - NODE_ENV=development
      # this is safe because it's only used for testing
      - SESSION_SECRET=LERTmi2Jiz6gJHt21AZUWBstezP41P3odxzEsCo1w4zL8XqGyjGdMZ2QPXUenVQQ2fY1xzGBYesB1g9teRHbxF
