port = 8080
trust_proxy = 2

[db]
mode = "postgres"
metrics = true

[redis]
metrics = true

[info_extractor.direct]
ffprobe_path = "/usr/bin/ffprobe"
ffprobe_strategy = "run"

[add_preview.search]
enabled = true
