port = 8080
trust_proxy = 2

[db]
mode = "postgres"
metrics = true

[redis]
metrics = true

[info_extractor.youtube]
truncate_description = 509

[info_extractor.direct]
ffprobe_path = "/usr/bin/ffprobe"
ffprobe_strategy = "stream"

[add_preview.search]
enabled = true
