app = "ott-balancer-prod"
primary_region = "ewr"

[build]
dockerfile = "balancer.Dockerfile"
build-target = "deploy-stage"

[build.args]
DEPLOY_TARGET = "ott-balancer-prod"

[deploy]
strategy = "bluegreen"

[http_service]
internal_port = 8081
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[http_service.concurrency]
type = "connections"
soft_limit = 400
hard_limit = 1000

[http_service.http_options]
h2_backend = true

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "10s"
path = "/api/status"

[metrics]
port = 8081
path = "/api/status/metrics"
