hostname = "staging.opentogethertube.com"
force_insecure_cookies = true
cors_proxy = "cors.opentogethertube.com"

[log]
level = "silly"

[[balancers]]
host = "ewr.ott-balancer-staging.internal"
port = 8081