hostname = "staging.opentogethertube.com"
force_insecure_cookies = true
cors_proxy = "cors.opentogethertube.com"

[log]
level = "silly"

[db]
metrics = false

[redis]
metrics = false

[balancing]
enabled = true
