version: "3.7"
services:
  opentogethertube:
    image: opentogethertube
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    container_name: opentogethertube
    environment:
      # nodejs
      - NODE_ENV=production
      - NODE_OPTIONS="--max-http-header-size=16000"
      # redis
      - REDIS_PORT=6379
      - REDIS_HOST=redis_db
      - REDIS_PASSWORD=redis
      # postgrep
      - DB_PASSWORD=postgres
      - DATABASE_URL=postgres://ott:postgres@db_opentogethertube_prod:5432
      - PORT=8080
    ports:
      - 8080:8080
    links:
      - redis_db
      - postgres_db
    depends_on:
      - redis_db
      - postgres_db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  redis_db:
    container_name: opentogethertube_redis
    image: redis
    environment:
      - REDIS_PASSWORD="redis"
      - REDIS_DB="opentogethertube"
    healthcheck:
      test: "redis-cli ping"
    expose:
      - 6379
    volumes:
      - db-data:/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  postgres_db:
    container_name: opentogethertube_postgres
    image: postgres
    environment:
      - POSTGRES_USER=ott
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_opentogethertube_prod
      - PGDATA=/var/lib/postgresql/data/db
    healthcheck:
      test: "pg_isready -U ott"
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

# shared volume
volumes:
  db-data:
    driver: local
