/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in .config/README.md
 */

/*
 * This utility function is useful in combination with jest `transformIgnorePatterns` config
 * to transform specific packages (e.g.ES modules) in a projects node_modules folder.
 */
const nodeModulesToTransform = moduleNames => `node_modules\/(?!.*(${moduleNames.join("|")})\/.*)`;

// Array of known nested grafana package dependencies that only bundle an ESM version
const grafanaESModules = [
	".pnpm", // Support using pnpm symlinked packages
	"@grafana/schema",
	"d3",
	"d3-color",
	"d3-force",
	"d3-interpolate",
	"d3-scale-chromatic",
	"d3-array",
	"d3-axis",
	"d3-brush",
	"d3-dispatch",
	"d3-drag",
	"d3-selection",
	"d3-transition",
	"d3-timer",
	"d3-ease",
	"d3-chord",
	"d3-path",
	"d3-contour",
	"d3-geo",
	"d3-delaunay",
	"d3-dsv",
	"d3-fetch",
	"d3-quadtree",
	"d3-format",
	"d3-hierarchy",
	"d3-polygon",
	"d3-random",
	"d3-scale",
	"d3-time",
	"d3-time-format",
	"d3-shape",
	"d3-zoom",
	"delaunator",
	"ol",
	"react-colorful",
	"rxjs",
	"uuid",
	"internmap",
	"robust-predicates",
];

module.exports = {
	nodeModulesToTransform,
	grafanaESModules,
};
