name: CI

on:
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "docs/**"
      - "env/**"
      - "**/*.md"
      - ".gitpod.yml"
  push:
    branches:
      - master
    paths-ignore:
      - ".vscode/**"
      - "docs/**"
      - "env/**"
      - "**/*.md"
      - ".gitpod.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node_modules-${{ runner.os }}-node-${{ matrix.node-version }}-
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn run lint-ci
        env:
          NODE_ENV: production

      - name: cargo-install
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typeshare-cli
          version: "1.7.0"
      - name: Ensure generated code is up to date
        run: ./scripts/codegen.sh && git diff --exit-code

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos-action
        uses: crate-ci/typos@v1.19.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: true
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node_modules-${{ runner.os }}-node-${{ matrix.node-version }}-
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn workspace ott-server run sequelize db:migrate
        env:
          NODE_ENV: test
      - run: yarn run build
      - run: yarn run test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
